# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  project: '**/*.csproj' # Ensure this points to the correct project file(s)
  tests: '**/*Tests/*.csproj' # Ensure this points to the test project(s)

steps:
# Install NuGet Tool
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

# Restore NuGet Packages
- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet Packages'
  inputs:
    command: 'restore'
    feedsToUse: 'select'
    includeNuGetOrg: true

# Run Unit Tests
- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests'
  inputs:
    command: 'test'
    projects: '$(tests)'
    arguments: '--configuration $(buildConfiguration)'

# Build and Publish Project
- task: DotNetCoreCLI@2
  displayName: 'Build and Publish Project'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(project)'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

# Publish Build Artifacts
- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'cloudtmsapi'
    publishLocation: 'Container'
